/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
/**
 *
 * @author adalb
 */
public class Institución_LAB1 extends javax.swing.JFrame {

    /**
     * Creates new form Institución_LAB1
     */
    public Institución_LAB1() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    private PalindromoAir palindromo=new PalindromoAir();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dispatch = new javax.swing.JButton();
        searchPassenger = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        printPassengers = new javax.swing.JButton();
        income = new javax.swing.JButton();
        firstAvailable1 = new javax.swing.JButton();
        sellTicket = new javax.swing.JButton();
        cancelTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispatch.setText("Dispatch");
        dispatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispatchActionPerformed(evt);
            }
        });

        searchPassenger.setText("Search Passenger");
        searchPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPassengerActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        printPassengers.setText("Print Passengers");
        printPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPassengersActionPerformed(evt);
            }
        });

        income.setText("Income");
        income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeActionPerformed(evt);
            }
        });

        firstAvailable1.setText("First Available");
        firstAvailable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstAvailable1ActionPerformed(evt);
            }
        });

        sellTicket.setText("Sell Ticket");
        sellTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTicketActionPerformed(evt);
            }
        });

        cancelTicket.setText("Cancel Ticket");
        cancelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstAvailable1)
                    .addComponent(cancelTicket)
                    .addComponent(sellTicket)
                    .addComponent(reset)
                    .addComponent(income)
                    .addComponent(printPassengers)
                    .addComponent(searchPassenger)
                    .addComponent(dispatch))
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(firstAvailable1)
                .addGap(28, 28, 28)
                .addComponent(searchPassenger)
                .addGap(33, 33, 33)
                .addComponent(printPassengers)
                .addGap(31, 31, 31)
                .addComponent(income)
                .addGap(32, 32, 32)
                .addComponent(reset)
                .addGap(40, 40, 40)
                .addComponent(sellTicket)
                .addGap(35, 35, 35)
                .addComponent(cancelTicket)
                .addGap(40, 40, 40)
                .addComponent(dispatch)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstAvailable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstAvailable1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Asiento disponible en la posicion: "+palindromo.firstAvailable());
    }//GEN-LAST:event_firstAvailable1ActionPerformed

    private void searchPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPassengerActionPerformed
        // TODO add your handling code here:
        String nombre=JOptionPane.showInputDialog("Ingrese el nombre del pasajero:");
        int pasajero=palindromo.searchPassenger(nombre);
        if(pasajero==-1){
            JOptionPane.showMessageDialog(null, "Este pasajero no existe");
        }else{
            JOptionPane.showMessageDialog(null, "El pasajero esta en el asiento: "+palindromo.searchPassenger(nombre));
        }
    }//GEN-LAST:event_searchPassengerActionPerformed

    private void sellTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTicketActionPerformed
        // TODO add your handling code here:
        String nombre=JOptionPane.showInputDialog("Ingrese su nombre:");
        palindromo.sellTicket(nombre);
    }//GEN-LAST:event_sellTicketActionPerformed

    private void printPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPassengersActionPerformed
        // TODO add your handling code here:
        palindromo.printPassengers();
    }//GEN-LAST:event_printPassengersActionPerformed

    private void cancelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketActionPerformed
        // TODO add your handling code here:
        if(palindromo.cancelTicket(JOptionPane.showInputDialog(this, "Ingrese el nombre del pasajero: ")) == true){
            JOptionPane.showMessageDialog(this, "El ticket ha sido cancelado");
        }else{
            JOptionPane.showMessageDialog(this, "Este ticket no existe");
        }
    }//GEN-LAST:event_cancelTicketActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        palindromo.reset();;
    }//GEN-LAST:event_resetActionPerformed

    private void incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "el ingreso es de: $ "+palindromo.Income());
    }//GEN-LAST:event_incomeActionPerformed

    private void dispatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispatchActionPerformed
        // TODO add your handling code here:
        palindromo.dispatch();
    }//GEN-LAST:event_dispatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Institución_LAB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Institución_LAB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Institución_LAB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Institución_LAB1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Institución_LAB1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelTicket;
    private javax.swing.JButton dispatch;
    private javax.swing.JButton firstAvailable1;
    private javax.swing.JButton income;
    private javax.swing.JButton printPassengers;
    private javax.swing.JButton reset;
    private javax.swing.JButton searchPassenger;
    private javax.swing.JButton sellTicket;
    // End of variables declaration//GEN-END:variables
}
